/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace CertificateRegistry {
      
    export type CertificateStruct = {issuer: AddressLike, student: AddressLike, certificateHash: BytesLike, issueDate: BigNumberish, status: BigNumberish}

    export type CertificateStructOutput = [issuer: string, student: string, certificateHash: string, issueDate: bigint, status: bigint] & {issuer: string, student: string, certificateHash: string, issueDate: bigint, status: bigint }
  
    }

  export interface CertificateRegistryInterface extends Interface {
    getFunction(nameOrSignature: "authorizeIssuer" | "authorizedIssuers" | "getCertificate" | "issueCertificate" | "owner" | "revokeCertificate" | "revokeIssuer" | "verifyCertificate"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CertificateIssued" | "CertificateRevoked" | "IssuerAuthorized" | "IssuerRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'authorizeIssuer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'authorizedIssuers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getCertificate', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'issueCertificate', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'revokeCertificate', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'revokeIssuer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verifyCertificate', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'authorizeIssuer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedIssuers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCertificate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'issueCertificate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeCertificate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeIssuer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyCertificate', data: BytesLike): Result;
  }

  
    export namespace CertificateIssuedEvent {
      export type InputTuple = [certificateID: BytesLike, issuer: AddressLike, student: AddressLike];
      export type OutputTuple = [certificateID: string, issuer: string, student: string];
      export interface OutputObject {certificateID: string, issuer: string, student: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CertificateRevokedEvent {
      export type InputTuple = [certificateID: BytesLike, revokedBy: AddressLike];
      export type OutputTuple = [certificateID: string, revokedBy: string];
      export interface OutputObject {certificateID: string, revokedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IssuerAuthorizedEvent {
      export type InputTuple = [issuer: AddressLike];
      export type OutputTuple = [issuer: string];
      export interface OutputObject {issuer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IssuerRevokedEvent {
      export type InputTuple = [issuer: AddressLike];
      export type OutputTuple = [issuer: string];
      export interface OutputObject {issuer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CertificateRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): CertificateRegistry;
    waitForDeployment(): Promise<this>;

    interface: CertificateRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    authorizeIssuer: TypedContractMethod<
      [issuer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    authorizedIssuers: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    getCertificate: TypedContractMethod<
      [certificateID: BytesLike, ],
      [CertificateRegistry.CertificateStructOutput],
      'view'
    >
    

    
    issueCertificate: TypedContractMethod<
      [student: AddressLike, certificateHash: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    revokeCertificate: TypedContractMethod<
      [certificateID: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeIssuer: TypedContractMethod<
      [issuer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifyCertificate: TypedContractMethod<
      [certificateID: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'authorizeIssuer'): TypedContractMethod<
      [issuer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'authorizedIssuers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getCertificate'): TypedContractMethod<
      [certificateID: BytesLike, ],
      [CertificateRegistry.CertificateStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'issueCertificate'): TypedContractMethod<
      [student: AddressLike, certificateHash: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'revokeCertificate'): TypedContractMethod<
      [certificateID: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeIssuer'): TypedContractMethod<
      [issuer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyCertificate'): TypedContractMethod<
      [certificateID: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'CertificateIssued'): TypedContractEvent<CertificateIssuedEvent.InputTuple, CertificateIssuedEvent.OutputTuple, CertificateIssuedEvent.OutputObject>;
getEvent(key: 'CertificateRevoked'): TypedContractEvent<CertificateRevokedEvent.InputTuple, CertificateRevokedEvent.OutputTuple, CertificateRevokedEvent.OutputObject>;
getEvent(key: 'IssuerAuthorized'): TypedContractEvent<IssuerAuthorizedEvent.InputTuple, IssuerAuthorizedEvent.OutputTuple, IssuerAuthorizedEvent.OutputObject>;
getEvent(key: 'IssuerRevoked'): TypedContractEvent<IssuerRevokedEvent.InputTuple, IssuerRevokedEvent.OutputTuple, IssuerRevokedEvent.OutputObject>;

    filters: {
      
      'CertificateIssued(bytes32,address,address)': TypedContractEvent<CertificateIssuedEvent.InputTuple, CertificateIssuedEvent.OutputTuple, CertificateIssuedEvent.OutputObject>;
      CertificateIssued: TypedContractEvent<CertificateIssuedEvent.InputTuple, CertificateIssuedEvent.OutputTuple, CertificateIssuedEvent.OutputObject>;
    

      'CertificateRevoked(bytes32,address)': TypedContractEvent<CertificateRevokedEvent.InputTuple, CertificateRevokedEvent.OutputTuple, CertificateRevokedEvent.OutputObject>;
      CertificateRevoked: TypedContractEvent<CertificateRevokedEvent.InputTuple, CertificateRevokedEvent.OutputTuple, CertificateRevokedEvent.OutputObject>;
    

      'IssuerAuthorized(address)': TypedContractEvent<IssuerAuthorizedEvent.InputTuple, IssuerAuthorizedEvent.OutputTuple, IssuerAuthorizedEvent.OutputObject>;
      IssuerAuthorized: TypedContractEvent<IssuerAuthorizedEvent.InputTuple, IssuerAuthorizedEvent.OutputTuple, IssuerAuthorizedEvent.OutputObject>;
    

      'IssuerRevoked(address)': TypedContractEvent<IssuerRevokedEvent.InputTuple, IssuerRevokedEvent.OutputTuple, IssuerRevokedEvent.OutputObject>;
      IssuerRevoked: TypedContractEvent<IssuerRevokedEvent.InputTuple, IssuerRevokedEvent.OutputTuple, IssuerRevokedEvent.OutputObject>;
    
    };
  }